In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
## Example usage
sent=['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am going to the market',
        'i am agood boy',
        'i am agood developer',
        'understand the meaning of words']

In [17]:
#define vocabulary size
voca_size=10000

In [18]:
#one hot representation 
onehot_repr=[one_hot(words,voca_size)for words in sent]
for item in onehot_repr:
    print(item)

[8598, 7262, 5219, 9008]
[8598, 7262, 5219, 8856]
[8598, 8702, 5219, 4743]
[5970, 9926, 4178, 8428, 8598, 2749]
[5970, 9926, 2498, 8974]
[5970, 9926, 2498, 9965]
[6492, 8598, 1392, 5219, 1186]


In [19]:
#word embeddings representation can be done using Embedding layer in keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences

In [20]:
import numpy as np


In [21]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8598 7262 5219 9008]
 [   0    0    0    0 8598 7262 5219 8856]
 [   0    0    0    0 8598 8702 5219 4743]
 [   0    0 5970 9926 4178 8428 8598 2749]
 [   0    0    0    0 5970 9926 2498 8974]
 [   0    0    0    0 5970 9926 2498 9965]
 [   0    0    0 6492 8598 1392 5219 1186]]


In [22]:
##feature represntation 
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voca_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\gen ai udemy\ann\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step


array([[[ 0.01428064,  0.00341075, -0.01464003,  0.02689681,
          0.02467687, -0.04247767, -0.02804201, -0.00843259,
          0.04424565,  0.02204927],
        [ 0.01428064,  0.00341075, -0.01464003,  0.02689681,
          0.02467687, -0.04247767, -0.02804201, -0.00843259,
          0.04424565,  0.02204927],
        [ 0.01428064,  0.00341075, -0.01464003,  0.02689681,
          0.02467687, -0.04247767, -0.02804201, -0.00843259,
          0.04424565,  0.02204927],
        [ 0.01428064,  0.00341075, -0.01464003,  0.02689681,
          0.02467687, -0.04247767, -0.02804201, -0.00843259,
          0.04424565,  0.02204927],
        [-0.01297861, -0.04779064,  0.02703602, -0.01614556,
          0.03671714, -0.02354981, -0.04194022, -0.00309541,
          0.01207274,  0.01704806],
        [-0.04379201, -0.00422741, -0.03033092,  0.00109953,
         -0.0427485 , -0.03056066, -0.03934766, -0.0351166 ,
          0.02420485,  0.00184294],
        [ 0.04241699,  0.00360114,  0.04276611,  0.0